### ISSUE TITLE
Clicking on "remix" throws uncaught exception

### ISSUE THREAD

**Issue by rahulkgupta** [3DStreet/3dstreet#566]
Branch: `main`
Env: `localhost`
scenario: Go to "funny waymo" scene. Click "remix"
Error:
```
ERROR
Cannot set properties of null (setting 'src')
TypeError: Cannot set properties of null (setting 'src')
    at _callee3$ (http://localhost:3333/dist/aframe-street-component.js:40272:30)
    at tryCatch (http://localhost:3333/dist/aframe-street-component.js:40122:1062)
    at Generator.<anonymous> (http://localhost:3333/dist/aframe-street-component.js:40122:3008)
    at Generator.next (http://localhost:3333/dist/aframe-street-component.js:40122:1699)
    at asyncGeneratorStep (http://localhost:3333/dist/aframe-street-component.js:40123:103)
    at _next (http://localhost:3333/dist/aframe-street-component.js:40124:194)

Error capturing screenshot and updating Firestore: TypeError: Cannot read properties of null (reading 'naturalWidth')
    at _callee$ (ScreenshotModal.component.jsx:33:48)
    at tryCatch (ScreenshotModal.component.jsx:2:1)
    at Generator.<anonymous> (ScreenshotModal.component.jsx:2:1)
    at Generator.next (ScreenshotModal.component.jsx:2:1)
    at asyncGeneratorStep (ScreenshotModal.component.jsx:2:1)
    at _next (ScreenshotModal.component.jsx:2:1)
```

Screenshot:
![Screenshot 2024-06-07 at 8 35 30 AM](https://github.com/3DStreet/3dstreet/assets/610372/c6e13d9c-f6bb-434e-b9de-552b97b866ad)

**Comment by rahulkgupta** [comment]
Assigning to @kfarr but please lmk if there's someone else i should assign.

**Comment by vincentfretin** [comment]
I selected the oldest "funny waymo" scene and clicked "remix" I don't reproduce.
Are you using the latest main? We merged the big street-geo-editor branch 1h before you created the issue.

**Comment by rahulkgupta** [comment]
works now. closing
