### ISSUE TITLE
undo error when using hand tool instead of pointer tool

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#698]
Steps:
- move an element
- click on hand tool
- click on undo button

This produces the following error:
```js
viewport.js:201 Uncaught TypeError: Cannot read properties of null (reading 'object3DMap')
    at EventEmitter.<anonymous> (viewport.js:201:34)
    at EventEmitter.emit (events.js:158:1)
    at EntityUpdateCommand.undo (EntityUpdateCommand.js:91:12)
    at History.undo (history.js:95:11)
    at Inspector.undo (index.js:237:18)
    at handleUndoClick (UndoRedo.component.jsx:16:22)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
```

**Comment by vincentfretin** [comment]
PR #708 fixes the issue.
